###########################################
# Constraints
###########################################
generate_state_vector = function(X){
  links = which(X>0,arr.ind = TRUE)
  links = links[links[,1]<links[,2],]
  Z = NULL
  for(k in 1:nrow(links)){
    ij = paste(c('','','n'),paste(paste(links[k,1],c('','n',''),sep=''),links[k,2],sep=''),sep='')
    Z = c(Z,ij)
  }
  isols = which(rowSums(X)==0)
  Z = c(Z,isols)
  return(Z)
}

generate_kappas = function(Z,gamma=10,K=4,criteria=1){
  if(criteria==1){
    k12 = gamma/(2*(gamma+1))*K
    kn12 = k12/gamma
    kappars =  c(k12,kn12,kn12,k12)
  }
  M = length(unique(sub('n','',Z)))
  kappa = rep(kappars,M)
  return(kappa)
}

generate_constraint_matrix = function(X){
  #'@param X is the adjacency matrix
  #'@value The constraint matrix A
  N = nrow(X)
  M = sum(X)/2
  N0 = sum(rowSums(X)==0)
  # The number of parameters is 3 x M
  
  links = which(X>0,arr.ind = TRUE)
  links = links[links[,1]<links[,2],]
  
  Z = generate_state_vector(X)
  
  A = NULL
  for(i in 1:N){
    rows = which(links[,1]==i | links[,2]==i)
    if(length(rows)>1){
      idx = c(sapply(rows,function(row){
        i1 = paste(links[row,1],links[row,2],sep='')
        he = links[row,1]
        ta = links[row,2]
        if(he==i){
          i2 = paste(links[row,1],links[row,2],sep='n')
        }else{
          i2 = paste('n',links[row,1],links[row,2],sep='')
        }
        return(c(i1,i2))
      }))
      R = length(idx)/2
      j = 1
      for(j in 1:(R-1)){
        Afila = rep(0,length(Z))
        relevants = which(is.element(Z,idx))
        Afila[relevants[2*(j-1)+1:2]] = 1
        Afila[relevants[2*(j)+1:2]] = -1
        A = rbind(A,Afila)
      }
    }
  }
  colnames(A)=Z
  rownames(A)=NULL
  return(A)
}

generate_proyector = function(A){
  require(MASS)
  K = Null(t(A))
  return(K)
}

proyect = function(z,K){
  #'@param z z is a matrix with each row representing an observation and each column a differen theta_rs
  #'@param K K is a matrix generated by generate_proyector
  #'@return The function returns a new z, already proyected
  coef = t(K)%*%t(z)
  z_ = t(K%*%coef)
  return(z_)
}

###########################################
# Densities
###########################################
check_z = function(zs){
  n = length(zs)/3
  flag=TRUE
  for(i in 1:n){
    z0 = zs[1:3 + (i-1)*3]
    flag = flag & (sum(z0)<=1 & all(z0>=0))
  }
  return(flag)
}


density_0 = function(z,params){
  #'@param z The value at which calculate the density
  #'@param params A list containing a vector kappa of length = length(z)+1
  #'@return The density evaluated at z
  kappa = params$kappa
  
  if(sum(z)>=1 | any(z<=0)){
    r = -Inf
  }else{
    r = sum((kappa[1:length(z)]-1)*log(z)) + (kappa[length(z)+1]-1)*log(1-sum(z))
    if(is.na(r)) r = -Inf
  }
  return(r)
}

density_comb = function(zs,params){
  #'@param zs A vector of 3 x number of links, representing each set of theta_rs
  #'@param params A list containing a vector kappas 
  kappas = params$kappas
  
  lL = 0
  n = length(zs)/3
  for(i in 1:n){
    z0 = zs[1:3 + (i-1)*3]
    kp = kappas[1:4 + (i-1)*4]
    lL = lL + density_0(z0,list('kappa'=kp))
  }
  return(lL)
}


density_eta = function(eta,params){
  #'@param eta Vector of hidden constrained theta_rs
  #'@param params A list containing a vector of kappas, and a proyector K and
  #'@return The density evaluated at the etas
  K = params$K 
  kappas = params$kappas
  
  z_ = as.numeric(K%*%eta)
  if(any(z_<=0 | z_>=1)){
    r = -Inf
  }else{
    r = density_comb(zs = z_,params = params)
  }
  return(r)
}

density_measure = function(z,params){
  #'@param z The value of z at which the measure density is evaluated
  #'@param params A list containing a vector of alfas and a matrix of measure H
  H = params$H 
  alfas = params$alfas
  flag = check_z(z)
  if(flag){
    m = H%*%z
    r = dbeta(m,alfas[1],alfas[2],log = TRUE)
  }else{
    r= -Inf
  }
  return(as.numeric(r))
}

density_measure_eta = function(eta,params){
  #'@param z The value of z at which the measure density is evaluated
  #'@param params A list containing a vector of alfas and a matrix of measure H, and a matrix of proyections K
  K = params$K 
  z = as.numeric(K%*%eta)
  if(any(z<=0) | any(z>=1) ){
    r = -Inf 
  }else{
    r = density_measure(z,params)
  }
  return(r)
}

density_posteriori = function(z,params){
  #'@param z The value of z at which the measure density is evaluated
  #'@param params A list containing a vector of alfas and a matrix of measure H, and a vector of kappas
  H = params$H 
  alfas = params$alfas
  kappas = params$kappas
  priori = density_comb(z,params)
  medicion = density_measure(z,params) 
  r = priori + medicion
  return(r)
}

density_posteriori_eta = function(eta,params){
  #'@param z The value of z at which the measure density is evaluated
  #'@param params A list containing a vector of alfas and a matrix of measure H, and a vector of kappas
  K = params$K 
  z = as.numeric(K%*%eta)
  priori = density_comb(z,params)
  medicion = density_measure(z,params) 
  r = priori + medicion
  return(r)
}

###########################################
# Sampling
###########################################

sampling = function(density,initial,params,nbatch=1e5,burnin=1e5,scale=1e-1,full.result=FALSE){
  require(mcmc)
  out = metrop(obj=density,initial=initial,params=params,nbatch = burnin,scale=scale)
  out = metrop(out,params=params, scale = scale,nbatch = nbatch)
  if(full.result){
    r = out
  }else{
    r = out$batch
  }
  return(r)
}

####################################################
###### OTHER
####################################################
make_ggmagic = function(df,gtitle='Priori'){
  gg12 = ggplot(data=df,aes(x=t12,y=t1n2))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) 
  gg13 = ggplot(data=df,aes(x=t12,y=tn12))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) + theme(legend.position = c(0.1,.7))
  gg23 = ggplot(data=df,aes(x=t1n2,y=tn12))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) + theme(legend.position = c(0.1,.7))
  gg1 = ggplot(data=df,aes(x=t12,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  gg2 = ggplot(data=df,aes(x=t1n2,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  gg3 = ggplot(data=df,aes(x=tn12,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  gL1 = (gg1+gg2+gg3)/(gg12+gg23+gg13)
  
  gg45 = ggplot(data=df,aes(x=t13,y=t1n3))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) 
  gg56 = ggplot(data=df,aes(x=t13,y=tn13))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) + theme(legend.position = c(0.1,.7))
  gg46 = ggplot(data=df,aes(x=t1n3,y=tn13))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) + theme(legend.position = c(0.1,.7))
  gg4 = ggplot(data=df,aes(x=t13,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  gg5 = ggplot(data=df,aes(x=t1n3,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  gg6 = ggplot(data=df,aes(x=tn13,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  gL2 = (gg4+gg5+gg6)/(gg45+gg56+gg46)
  
  gg14 = ggplot(data=df,aes(x=t12,y=t13))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) 
  gg25 = ggplot(data=df,aes(x=t1n2,y=t1n3))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) 
  gg36 = ggplot(data=df,aes(x=tn12,y=tn13))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) 
  gL3 = gg14+gg25+gg36
  
  ggA = ggplot(data=df,aes(x=t12+t1n2,y=t12+tn12))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) 
  ggB = ggplot(data=df,aes(x=t12+t1n2,y=t13+tn13))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) + theme(legend.position = c(0.1,.7))
  ggC = ggplot(data=df,aes(x=t12+tn12,y=t13+tn13))+ ggtitle(label=gtitle) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) + theme(legend.position = c(0.1,.7))
  ggD = ggplot(data=df,aes(x=t12+t1n2,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  ggE = ggplot(data=df,aes(x=t12+tn12,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  ggF = ggplot(data=df,aes(x=t13+tn13,y=..density..))+ ggtitle(label=gtitle) + geom_histogram() + xlim(c(0,1))  #+ ylim(c(0,1))
  gL4 = (ggD+ggE+ggF)/(ggA+ggB+ggC)
  
  return(list('gL1'=gL1,'gL2'=gL2,'gL3'=gL3,'gL4'=gL4))
}

make_ggmagic2 = function(df,dfP,gtitle1='Priori',gtitle2='Post'){
  A = (ggplot(data=df,aes(x=t12+t1n2,y=t13+t1n3))+ ggtitle(label=gtitle1) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) ) + (ggplot(data=dfP,aes(x=t12+t1n2,y=t13+t1n3))+ ggtitle(label=gtitle2) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) )
  B = (ggplot(data=df,aes(x=t12,y=t13))+ ggtitle(label=gtitle1) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) ) + (ggplot(data=dfP,aes(x=t12,y=t13))+ ggtitle(label=gtitle2) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) )
  C = (ggplot(data=df,aes(x=t1n2,y=t1n3))+ ggtitle(label=gtitle1) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) ) + (ggplot(data=dfP,aes(x=t1n2,y=t1n3))+ ggtitle(label=gtitle2) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) )
  D = (ggplot(data=df,aes(x=tn12,y=tn13))+ ggtitle(label=gtitle1) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) ) + (ggplot(data=dfP,aes(x=tn12,y=tn13))+ ggtitle(label=gtitle2) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) )
  E = (ggplot(data=df,aes(x=1-t12-tn12-t1n2,y=1-t13-t1n3-tn13))+ ggtitle(label=gtitle1) + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) ) + (ggplot(data=dfP,aes(x=1-t12-tn12-t1n2,y=1-t13-t1n3-tn13))+ ggtitle(label='Post') + geom_bin2d(show.legend=FALSE) + xlim(c(0,1)) + ylim(c(0,1)) )
  F = (ggplot(data=df,aes(x=t12+t1n2,y=..density..))+ ggtitle(label=gtitle1) + geom_histogram(show.legend=FALSE) + xlim(c(0,1)))  + (ggplot(data=dfP,aes(x=t12+t1n2,y=..density..))+ ggtitle(label=gtitle2) + geom_histogram(show.legend=FALSE) + xlim(c(0,1)))
  G = (ggplot(data=df,aes(x=t12+tn12,y=..density..))+ ggtitle(label=gtitle1) + geom_histogram(show.legend=FALSE) + xlim(c(0,1)))  + (ggplot(data=dfP,aes(x=t12+tn12,y=..density..))+ ggtitle(label=gtitle2) + geom_histogram(show.legend=FALSE) + xlim(c(0,1)))
  H = (ggplot(data=df,aes(x=t13+tn13,y=..density..))+ ggtitle(label=gtitle1) + geom_histogram(show.legend=FALSE) + xlim(c(0,1)))  + (ggplot(data=dfP,aes(x=t13+tn13,y=..density..))+ ggtitle(label=gtitle2) + geom_histogram(show.legend=FALSE) + xlim(c(0,1)))
  return(list('A'=A,'B'=B,'C'=C,'D'=D,'E'=E,'F'=F,'G'=G,'H'=H))
}
